# Generated by Django 3.2.11 on 2022-12-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('excerpt', models.TextField()),
                ('url', models.CharField(max_length=255, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('news_site_url', models.CharField(max_length=255)),
                ('dtstr', models.CharField(default='None', max_length=50)),
                ('posting_date', models.DateTimeField(auto_now_add=True)),
                ('media', models.CharField(default='None', max_length=255)),
            ],
        ),
    ]
