# Generated by Django 3.2.11 on 2022-11-30 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchPhrase', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('excerpt', models.TextField()),
                ('url', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('news_site_url', models.CharField(max_length=255)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.phrase')),
            ],
        ),
    ]
