# Generated by Django 3.2.11 on 2022-11-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='dtstr',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
