# Generated by Django 3.2.11 on 2022-11-30 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_dtstr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='phrase',
        ),
        migrations.DeleteModel(
            name='Phrase',
        ),
    ]
