# Generated by Django 3.2.11 on 2022-12-03 05:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20221130_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='posting_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
