# Generated by Django 3.2.11 on 2022-12-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='media',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='posting_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
