# Generated by Django 3.2.11 on 2022-12-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20221218_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='posting_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
