daily_news = [
    {
        "title": "VP Duterte has terse, cold remark on Joma's passing",
        "author": "Raymund Antonio",
        "published_date": "2022-12-17 07:29:00",
        "dtstr": "2022-12-17 07:29:00",
        "published_date_precision": "full",
        "link": "https://mb.com.ph/2022/12/17/vp-duterte-has-terse-cold-remark-on-jomas-passing/",
        "clean_url": "mb.com.ph",
        "excerpt": "\"May God have mercy on his soul.\"\n\r\rThis was the short and dispassionate reaction of Vice President Sara Duterte after she learned of the death of Communist Party of the Philippines (CPP) founder Jose Maria 'Joma' Sison at a hospital in The Netherlands, Friday night, Dec. 16.\n\nVice President Sara Du",
        "summary": "More from us:\n\n\nPressReader \n\n\n\n\n\n\n\n\n\n\n\n \n \n\n\n\n\n\n\n \n\n'May God have mercy on his soul.'\nThis was the short and dispassionate reaction of Vice President Sara Duterte after she learned of the death of Communist Party of the Philippines (CPP) founder Jose Maria 'Joma' Sison at a hospital in The Netherlands, Friday night, Dec. 16.\n\nVice President Sara Duterte (left) and CPP founder Joma Sison (right) (Photos from OVP/Joma Sison/Facebook)\n It can be recalled that the Vice President and her father, former president Rodrigo Duterte, have been outspoken about their distaste for Sison, whose party, together with its armed component the New People's Army (NPA), has waged a rebellion to overthrow the government for more than 50 years.",
        "rights": "mb.com.ph",
        "rank": 5693,
        "topic": "news",
        "country": "PH",
        "language": "en",
        "authors": "Raymund Antonio",
        "media": "https://mb.com.ph/wp-content/uploads/2022/12/117119.jpeg",
        "is_opinion": False,
        "twitter_account": None,
        "_score": None,
        "_id": "aad1d10904e74474eb02f758e9dd0e48",
    },
    {
        "title": "P300 million giant clams seized in Tabogon",
        "author": "SUNSTAR",
        "published_date": "2022-12-17 07:23:58",
        "dtstr": "2022-12-17 07:23:58",
        "published_date_precision": "full",
        "link": "https://www.sunstar.com.ph/article/1948814/cebu/local-news/p300-million-giant-clams-seized-in-tabogon",
        "clean_url": "sunstar.com.ph",
        "excerpt": "MORE than P300 million worth of giant clams (taklobo) were confiscated in a joint buy-bust operation by the Provincial Intelligence Unit, Provincial Drug Enforcement Unit, Tabogon...",
        "summary": "Google map MORE than P300 million worth of giant clams (taklobo) were confiscated in a joint buy-bust operation by the Provincial Intelligence Unit, Provincial Drug Enforcement Unit, Tabogon Police Station and Bureau of Fisheries and Aquatic Resources in Sitio Gutob, Barangay Camoboan, Tabogon town, northern Cebu around 9 a.m. on Thursday, December 15, 2022.Natividad Nueva Ruiz, 76, the alleged trader of the endangered sea creatures, was also arrested during the operation, which was in coordination with the Naval Forces Central, Philippine Coast Guard Special Operating Unit Northern Cebu and the Philippine Air Force.",
        "rights": "Copyright 2022,SUNSTAR",
        "rank": 16539,
        "topic": "news",
        "country": "PH",
        "language": "en",
        "authors": "SUNSTAR",
        "media": "https://www.sunstar.com.ph/uploads/images/2022/12/17/402327.jpg",
        "is_opinion": False,
        "twitter_account": None,
        "_score": None,
        "_id": "297bf23c36f236d4fd9b7e66f9b9fd8c",
    },
    {
        "title": "42 TESDA scholars in Quezon receive tool kits from provincial board member",
        "author": "Danny Estacio",
        "published_date": "2022-12-17 07:21:00",
        "dtstr": "2022-12-17 07:21:00",
        "published_date_precision": "full",
        "link": "https://mb.com.ph/2022/12/17/42-tesda-scholars-in-quezon-receive-tool-kits-from-provincial-board-member/",
        "clean_url": "mb.com.ph",
        "excerpt": "QUEZON Provincial Board member Jet Suarez gives the thumbs-up after the distribution of tool kits and awarding of certificates to 42 scholars from Mulanay and Catanauan, Quezon who finished a TESDA short course. (Jet Suarez FB)\n\r\rMULANAY, Quezon – Forty-two Technical Education and Skills Development",
        "summary": "More from us:\n\n\nPressReader \n\n\n\n\n\n\n\n\n\n\n\n \n \n\n\n\n\n\n\n \n \nQUEZON Provincial Board member Jet Suarez gives the thumbs-up after the distribution of tool kits and awarding of certificates to 42 scholars from Mulanay and Catanauan, Quezon who finished a TESDA short course. (Jet Suarez FB)\n MULANAY, Quezon – Forty-two Technical Education and Skills Development Authority scholars from this town and Catanauan, this province, have completed a short course and received tool kits from Quezon Provincial Board Member Jet Suarez.",
        "rights": "mb.com.ph",
        "rank": 5693,
        "topic": "news",
        "country": "PH",
        "language": "en",
        "authors": "Danny Estacio",
        "media": "https://mb.com.ph/wp-content/uploads/2022/12/117118.jpeg",
        "is_opinion": False,
        "twitter_account": None,
        "_score": None,
        "_id": "722a981cb9b830d439dbd864a95b8a88",
    },
    {
        "title": "GMA Pinoy TV hosts Fil-Am leaders for Thanksgiving, Network visit",
        "author": "Manila Bulletin Entertainment",
        "published_date": "2022-12-17 07:17:20",
        "dtstr": "2022-12-17 07:17:20",
        "published_date_precision": "full",
        "link": "https://mb.com.ph/2022/12/17/gma-pinoy-tv-hosts-fil-am-leaders-for-thanksgiving-network-visit/",
        "clean_url": "mb.com.ph",
        "excerpt": "FYLPRO delegates Leading broadcast company GMA Network, through its flagship international channel GMA Pinoy TV, recently opened its doors to the 15 delegates of the Filipino Young Leaders Program…",
        "summary": "FYLPRO delegates\nLeading broadcast company GMA Network, through its flagship international channel GMA Pinoy TV, recently opened its doors to the 15 delegates of the Filipino Young Leaders Program (FYLPRO) last Nov. 24 during their week-long immersion trip to the Philippines. \nWelcoming them is GMA International First Vice President and Head of Operations Joseph Jerome T. Francia who accompanied them in their full Kapuso experience. \n'We are delighted to have the excellent delegates of this year's FYLPRO in GMA.",
        "rights": "mb.com.ph",
        "rank": 5693,
        "topic": "news",
        "country": "PH",
        "language": "en",
        "authors": "Manila Bulletin Entertainment",
        "media": "https://mb.com.ph/wp-content/uploads/2022/12/FYLPRO-delegates-1024x576.jpeg",
        "is_opinion": False,
        "twitter_account": None,
        "_score": None,
        "_id": "cb3dfafb7f5211e7bef7e6754bddfa6c",
    },
    {
        "title": "Zavier Lucero sits out Game 3, ends UAAP career with ACL injury",
        "author": "",
        "published_date": "2022-12-17 07:16:10",
        "dtstr": "2022-12-17 07:16:10",
        "published_date_precision": "full",
        "link": "https://mb.com.ph/2022/12/17/zavier-lucero-sits-out-game-3-ends-uaap-career-with-acl-injury/",
        "clean_url": "mb.com.ph",
        "excerpt": "Zavier Lucero of University of the Philippines. (UAAP Media) By NIKOLE JAVIER Zavier Lucero will not only sit out the winner-take-all Game 3 between University of the Philippines and Ateneo, but he'll…",
        "summary": "Zavier Lucero of University of the Philippines. (UAAP Media) \nBy NIKOLE JAVIER \nZavier Lucero will not only sit out the winner-take-all Game 3 between University of the Philippines and Ateneo, but he'll be ending his UAAP career with a torn ACL. \nThe 6-foot-6 forward, who was present during the Fighting Maroons' practice on Friday, Dec. 16, tearfully broke the news to his teammates. \nLucero, who committed to UP after his eligibility in Season 84 earlier this year, played hero for the Fighting Maroons in their historic championship run and in the season that followed.",
        "rights": "mb.com.ph",
        "rank": 5693,
        "topic": "news",
        "country": "PH",
        "language": "en",
        "authors": "",
        "media": "https://mb.com.ph/wp-content/uploads/2022/12/UAAP85-MBB-ZAVIER-LUCERO-2-1024x682.jpg",
        "is_opinion": False,
        "twitter_account": None,
        "_score": None,
        "_id": "479c565b720786877be937131fa56e77",
    },
    {
        "title": "Get a dose of Eraserheads at Hard Rock Café Makati's Tribute Night Dec. 21",
        "author": "Manila Bulletin Entertainment",
        "published_date": "2022-12-17 07:05:18",
        "dtstr": "2022-12-17 07:05:18",
        "published_date_precision": "full",
        "link": "https://mb.com.ph/2022/12/17/get-a-dose-of-eraserheads-at-hard-rock-cafe-makatis-tribute-night-dec-21/",
        "clean_url": "mb.com.ph",
        "excerpt": "The music of iconic Filipino rock band, Eraserheads, will be at the limelight at Hard Rock Café's Glorietta branch on Dec. 21. Rock to Eheads' greatest hits such as With A Smile, Ang Huling El Bimbo &…",
        "summary": "The music of iconic Filipino rock band, Eraserheads, will be at the limelight at Hard Rock Café's Glorietta branch on Dec. 21. \n Rock to Eheads' greatest hits such as With A Smile, Ang Huling El Bimbo & more to be performed by Bluegrass. Show starts at 8 pm.\n\nEntrance fee is P395 per head inclusive of a complimentary beverage. Contact  (02) 79003355 for inquiries and to reservations. \nHard Rock Cafe Makati is located at the ground floor of Glorietta 3, beside mall entranceFind them on Facebook &",
        "rights": "mb.com.ph",
        "rank": 5693,
        "topic": "news",
        "country": "PH",
        "language": "en",
        "authors": "Manila Bulletin Entertainment",
        "media": "https://mb.com.ph/wp-content/uploads/2022/12/EHEADS2-1-1024x715.jpg",
        "is_opinion": False,
        "twitter_account": None,
        "_score": None,
        "_id": "144c4d66ac2353fc240e200b7dab3b9d",
    },
    {
        "title": "Tricycle driver, patay matapos masalpok ng truck sa Pagbilao, Quezon",
        "author": "PEEWEE BACUÑO",
        "published_date": "2022-12-17 07:04:32",
        "dtstr": "2022-12-17 07:04:32",
        "published_date_precision": "timezone unknown",
        "link": "https://www.gmanetwork.com/news/balitambayan/promdi/854754/tricycle-driver-patay-matapos-masalpok-ng-truck-sa-pagbilao-quezon/story/",
        "clean_url": "gmanetwork.com",
        "excerpt": "Patay ang isang tricycle driver matapos salpukin ng isang forward truck ang minamaneho nitong tricycle sa Maharlika Highway, Pinagbayanan, Pagbilao, Quezon pasado alas-siyete ng gabi nitong Biyernes.",
        "summary": "PAGBILAO, Quezon - Patay ang isang tricycle driver matapos salpukin ng isang forward truck ang minamaneho nitong tricycle sa Maharlika Highway, Pinagbayanan, Pagbilao, Quezon pasado alas-siyete ng gabi nitong Biyernes. Ayon sa report ng Pagbilao Municipal Police station, binabagtas ng truck ang Maharlika Highway patungo sa direksyon ng Maynila nang mag-overtake ito at salpukin ang kasalubong na tricycle na nasa kabilang linya. Sa tindi ng pagsalpok ay wasak na wasak ang tricycle. Mabilis na na-rescue ang driver at isinugod sa pagamutan sa Lucena City subalit idineklara itong dead on arrival sa pagamutan.",
        "rights": " Copyright 2022 GMA Network and www.gmanetwork.com/news. Unauthorized use and/or duplication of this material without express and written permission from this site's owner is strictly prohibited. Excerpts and links may be used, provided that full and clear credit is given to GMA Network and GMA News Online with appropriate and specific direction to the original content.",
        "rank": 5469,
        "topic": "news",
        "country": "PH",
        "language": "tl",
        "authors": "PEEWEE BACUÑO",
        "media": "https://images.gmanews.tv/webpics/2022/12/accident_2022_12_17_06_56_43.jpeg",
        "is_opinion": False,
        "twitter_account": "@gmanews",
        "_score": None,
        "_id": "9b27e6b10d6906a4f047f2d898bb4027",
    },
    {
        "title": "Oaminal clan expands gift-giving tradition, gives away noche buena packs",
        "author": "Ellson Quismorio",
        "published_date": "2022-12-17 07:04:00",
        "dtstr": "2022-12-17 07:04:00",
        "published_date_precision": "full",
        "link": "https://mb.com.ph/2022/12/17/oaminal-clan-expands-gift-giving-tradition-gives-away-noche-buena-packs/",
        "clean_url": "mb.com.ph",
        "excerpt": "</",
        "summary": "More from us:\n\n\nPressReader \n\n\n\n\n\n\n\n\n\n\n\n \n \n\n\n\n\n\n\n \n\nMisamis Occidental 2nd district Rep. Ando Oaminal helped kicked off the political clan's 'expanded' gift-giving tradition for local folk ahead of Christmas. \nMisamis Occidental 2nd district Rep. Ando Oaminal (2nd from left) leads the distribution of gift packs to local residents at the City Gym on Dec.8, 2022. (Facebook)\n Oaminal was at the City Gym in Lam-an, Ozamiz City last Dec. 8 for the distribution of Christmas gifts packs to his constituents.",
        "rights": "mb.com.ph",
        "rank": 5693,
        "topic": "news",
        "country": "PH",
        "language": "en",
        "authors": "Ellson Quismorio",
        "media": "https://mb.com.ph/wp-content/uploads/2022/12/117116.jpeg",
        "is_opinion": False,
        "twitter_account": None,
        "_score": None,
        "_id": "5b623190c13a32ed1c11656ed26ccd81",
    },
    {
        "title": "Man gunned down in Negros",
        "author": "Glazyl Masculino",
        "published_date": "2022-12-17 06:45:00",
        "dtstr": "2022-12-17 06:45:00",
        "published_date_precision": "full",
        "link": "https://mb.com.ph/2022/12/17/man-gunned-down-in-negros/",
        "clean_url": "mb.com.ph",
        "excerpt": "A POLICE officer checks the crime scene in Barangay Mambaroto, Sipalay City, Negros Occidental where a man was shot dead and his companion wounded on Wednesday. (Photo courtesy of Sipalay City Police Station)\n\n\n\r\rBACOLOD CITY – A 40-year-old man was killed while his friend was wounded in a shooting",
        "summary": "More from us:\n\n\nPressReader \n\n\n\n\n\n\n\n\n\n\n\n \n \n\n\n\n\n\n\n \n \nA POLICE officer checks the crime scene in Barangay Mambaroto, Sipalay City, Negros Occidental where a man was shot dead and his companion wounded on Wednesday. (Photo courtesy of Sipalay City Police Station)\n\n BACOLOD CITY – A 40-year-old man was killed while his friend was wounded in a shooting incident in Sitio Camp Valdez, Barangay Mambaroto, Sipalay City, Negros Occidental on Wednesday, Dec. 14.\nThe fatality was identified as Jomel Espora of Barangay 5, Sipalay City.",
        "rights": "mb.com.ph",
        "rank": 5693,
        "topic": "news",
        "country": "PH",
        "language": "en",
        "authors": "Glazyl Masculino",
        "media": "https://mb.com.ph/wp-content/uploads/2022/12/117113.jpeg",
        "is_opinion": False,
        "twitter_account": None,
        "_score": None,
        "_id": "43826f9b80e6bcedf99281ee71e3df69",
    },
    {
        "title": "Rolando Nolte best PH finisher in Manny Pacquiao International chess tourney",
        "author": "Kristel Satumbaga-Villar",
        "published_date": "2022-12-17 06:40:00",
        "dtstr": "2022-12-17 06:40:00",
        "published_date_precision": "full",
        "link": "https://mb.com.ph/2022/12/17/rolando-nolte-best-ph-finisher-in-manny-pacquiao-international-chess-tourney/",
        "clean_url": "mb.com.ph",
        "excerpt": "International Master Rolando Nolte shocked third seed Grandmaster Vitaly Sivuk of Sweden to finish third behind eventual champion Konstantin Sek of FIDE at the close of the MCPL's Manny Pacquiao International Open Chess Festival in General Santos City Saturday, Dec. 17.\n\r\r\n\nRolando Nolte finishes th",
        "summary": "More from us:\n\n\nPressReader \n\n\n\n\n\n\n\n\n\n\n\n \n \n\n\n\n\n\n\n \n\nInternational Master Rolando Nolte shocked third seed Grandmaster Vitaly Sivuk of Sweden to finish third behind eventual champion Konstantin Sek of FIDE at the close of the MCPL's Manny Pacquiao International Open Chess Festival in General Santos City Saturday, Dec. 17. \nRolando Nolte finishes third overall in the Manny Pacquiao International Open Chess Festival. (Photo from James Infiesto's Facebook page)\n Nolte, 50, actually wound up in a three-way tie on top with seven points along with Russian-born Sek and second seed Lucas Van Foreest of the Netherlands but settled for the bronze after tiebreaks were applied.",
        "rights": "mb.com.ph",
        "rank": 5693,
        "topic": "news",
        "country": "PH",
        "language": "en",
        "authors": "Kristel Satumbaga-Villar",
        "media": "https://mb.com.ph/wp-content/uploads/2022/12/117112.jpeg",
        "is_opinion": False,
        "twitter_account": None,
        "_score": None,
        "_id": "1ced48dcd585db6460392157ca38429e",
    },
    {
        "title": "Commemorative medals to be issued to mark BTS' 10th anniversary",
        "author": "Jonathan Hic",
        "published_date": "2022-12-17 06:39:30",
        "dtstr": "2022-12-17 06:39:30",
        "published_date_precision": "full",
        "link": "https://mb.com.ph/2022/12/17/commemorative-medals-to-be-issued-to-mark-bts-10th-anniversary/",
        "clean_url": "mb.com.ph",
        "excerpt": "Grammy-nominated K-pop idol group BTS will mark their 10th anniversary in June next year and ahead of the milestone, commemorative medals will be issued. The Korea Minting, Security Printing and ID…",
        "summary": "Grammy-nominated K-pop idol group BTS will mark their 10th anniversary in June next year and ahead of the milestone, commemorative medals will be issued. \nThe Korea Minting, Security Printing and ID Card Operating Corporation (KOMSCO; the sole manufacturer of South Korea's currency, announced that commemorative medals will be issued for BTS' 10th anniversary.\nThe BTS commemorative medals (KOMSCO) \nThe BTS commemorative medals (KOMSCO) \nThe BTS commemorative medals (KOMSCO) \nBTS (Big Hit Music) \nA total of 87,777 commemorative and limited edition medals will be made in three types of gold and one type of silver.",
        "rights": "mb.com.ph",
        "rank": 5693,
        "topic": "news",
        "country": "PH",
        "language": "en",
        "authors": "Jonathan Hicap",
        "media": "https://mb.com.ph/wp-content/uploads/2022/12/BTSCOIN1A.jpg",
        "is_opinion": False,
        "twitter_account": None,
        "_score": None,
        "_id": "0069de8da0961bf07889e92c2c99854d",
    },
    {
        "title": "D&L, CCPI to expand personal care business",
        "author": "James A. Loyola",
        "published_date": "2022-12-17 06:28:00",
        "dtstr": "2022-12-17 06:28:00",
        "published_date_precision": "full",
        "link": "https://mb.com.ph/2022/12/17/dl-ccpi-to-expand-personal-care-business/",
        "clean_url": "mb.com.ph",
        "excerpt": "Consumer Care Products Inc. (CCPI), the privately-owned marketing arm of Jadel Holdings, and sister company of D&L Industries Inc. are planning to grow their personal care business by tapping the…",
        "summary": "Consumer Care Products Inc. (CCPI), the privately-owned marketing arm of Jadel Holdings, and sister company of D&L Industries Inc. are planning to grow their personal care business by tapping the upscale market which has a growing preference for healthy and all-natural products.\nIn an interview, D&L President and CEO Alvin Lao said D&L develops and manufactures CCPI's branded consumer products which are mostly greener alternatives to petrochemicals-based personal and home care products. \nD&L Industries President Alvin D.",
        "rights": "mb.com.ph",
        "rank": 5693,
        "topic": "news",
        "country": "PH",
        "language": "en",
        "authors": "James A. Loyola",
        "media": "https://mb.com.ph/wp-content/uploads/2022/12/117108.jpeg",
        "is_opinion": False,
        "twitter_account": None,
        "_score": None,
        "_id": "747fe4df1ca1fae2ad38e1c54ec7d04b",
    },
]
